# docker-compose.yml文件的版本
version: "3.0"

# 管理的服务
services:
  es01:
    # 指定镜像
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    image: faber/es:7.9.2
    build: .
    container_name: es01
    ports:
      # 端口映射
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es/data:/usr/share/elasticsearch/data # 索引数据
      - ./es/analysis:/usr/share/elasticsearch/config/analysis # 同义词外部定义
      - ./IKAnalyzer.cfg.xml:/usr/share/elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml # IKAnalyzer分词器
    environment:
      - TZ="Asia/Shanghai"
      - node.name=es01
      - discovery.type=single-node
      # - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # 本地开发空间不够了，设置如下。服务器注释下面部分 --- begin
      - cluster.routing.allocation.disk.threshold_enabled=true # 是否启用功能
      - cluster.routing.allocation.disk.watermark.flood_stage=5gb # 到达后节点数据无法写入
      - cluster.routing.allocation.disk.watermark.low=15gb # 到达就停止创建新shards
      - cluster.routing.allocation.disk.watermark.high=10gb # 到达后会迁移现有shards到其他节点
      # 本地开发空间不够了，设置如下 --- end
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  # 图形管理界面
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    ports:
      - 5601:5601
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - TZ="Asia/Shanghai"
      - ELASTICSEARCH_HOSTS=http://es01:9200 # connect the es-balance node
      - I18N_LOCALE=zh-CN #汉化
      - xpack.monitoring.ui.container.elasticsearch.enabled=false
    networks:
      - elastic

  # logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.2
    container_name: logstash
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    depends_on:
      - "es01"
    ports:
      - 5044:5044
      - 9600:9600
    environment:
      - TZ="Asia/Shanghai"
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro   #主配置文件
      # - ./logstash/logstash_jdbc_last_run:/usr/share/logstash/logstash_jdbc_last_run:rw   #mysql
      - ./logstash/mysql-connector-java-8.0.27.jar:/usr/share/logstash/mysql-connector-java-8.0.27.jar:rw   #mysql
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro  #pipeline 配置文件
    networks:
      - elastic
  
  # nginx代理IKanalyzer的远程扩展字典、停止词字典
  es-ik-nginx:
    image: nginx
    container_name: es-ik-nginx
    # ports:
    #   - "80:80"
    #   - "443:443"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/etc/nginx/html
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge